insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"Yolo", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"This world is cool.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"This world is rad.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"This world is weird.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"This world is interesting.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("blue", 
			"123124325425", 
			now(), 
			0, 
			"This world is magnificent.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("#ffffff", 
			"123124325425", 
			now(), 
			0, 
			"This world is union.", 
			24, 
			"sans-serif", 
			"#000000");

insert into thoughts (color, 
					  geolocation, 
					  submitted, 
					  user, 
					  thought, 
					  font_size, 
					  font, 
					  font_color) 
	values ("#ffffff", 
			"123124325425", 
			now(), 
			0, 
			"This world is love.", 
			24, 
			"sans-serif", 
			"#000000");